import {
  User,
  Cliente,
  Documento,
  Incidencia,
  MetricasDashboard,
  ActividadReciente,
  DatosFinancieros,
} from '@/types';

// Mock Usuarios
export const mockUsuarios: User[] = [
  {
    id: '1',
    nombre: 'Admin Principal',
    email: 'admin@externaliza2.com',
    rol: 'admin',
    estado: 'activo',
    telefono: '+34 600 000 001',
    fechaAlta: new Date('2024-01-01'),
    ultimoAcceso: new Date('2025-10-23T09:00:00'),
  },
  {
    id: '2',
    nombre: 'Marta López García',
    email: 'marta@externaliza2.com',
    rol: 'asesor',
    estado: 'activo',
    telefono: '+34 600 000 002',
    fechaAlta: new Date('2024-01-15'),
    ultimoAcceso: new Date('2025-10-23T08:30:00'),
    clientesAsignados: ['c1', 'c2', 'c3', 'c4', 'c5'],
  },
  {
    id: '3',
    nombre: 'Luis Pérez Martín',
    email: 'luis@externaliza2.com',
    rol: 'asesor',
    estado: 'activo',
    telefono: '+34 600 000 003',
    fechaAlta: new Date('2024-02-01'),
    ultimoAcceso: new Date('2025-10-22T17:45:00'),
    clientesAsignados: ['c6', 'c7', 'c8'],
  },
  {
    id: '4',
    nombre: 'Carmen Ruiz Sánchez',
    email: 'carmen@externaliza2.com',
    rol: 'asesor',
    estado: 'activo',
    telefono: '+34 600 000 004',
    fechaAlta: new Date('2024-03-01'),
    ultimoAcceso: new Date('2025-10-23T07:00:00'),
    clientesAsignados: ['c9', 'c10'],
  },
  {
    id: '5',
    nombre: 'María García',
    email: 'contacto@energiasur.com',
    rol: 'cliente',
    estado: 'activo',
    telefono: '+34 600 111 222',
    fechaAlta: new Date('2024-01-20'),
    ultimoAcceso: new Date('2025-10-22T16:30:00'),
    asesoresAsignados: ['2'],
    modulosActivos: {
      subidaDocumentos: true,
      incidencias: true,
      asistenteE2: true,
      panelFinanciero: true,
      facturacion: false,
    },
  },
];

// Mock Clientes (expandido)
export const mockClientes: Cliente[] = [
  {
    id: 'c1',
    nif: 'B12345678',
    razonSocial: 'EnergíaSur SL',
    nombreComercial: 'EnergíaSur',
    personaContacto: 'María García',
    telefono: '+34 600 111 222',
    email: 'contacto@energiasur.com',
    direccionFiscal: 'Calle Principal 123, 41001 Sevilla',
    asesoresAsignados: ['2'],
    modulosActivos: {
      subidaDocumentos: true,
      incidencias: true,
      asistenteE2: true,
      panelFinanciero: true,
      facturacion: false,
    },
    estado: 'activo',
    fechaAlta: new Date('2024-01-20'),
  },
  {
    id: 'c2',
    nif: 'B87654321',
    razonSocial: 'ComexPro SL',
    nombreComercial: 'ComexPro',
    personaContacto: 'Carlos Martínez',
    telefono: '+34 600 333 444',
    email: 'info@comexpro.com',
    direccionFiscal: 'Avenida Comercio 45, 28001 Madrid',
    asesoresAsignados: ['2'],
    modulosActivos: {
      subidaDocumentos: true,
      incidencias: true,
      asistenteE2: false,
      panelFinanciero: false,
      facturacion: false,
    },
    estado: 'activo',
    fechaAlta: new Date('2024-02-10'),
  },
  {
    id: 'c3',
    nif: 'B11223344',
    razonSocial: 'GastroLuz SL',
    nombreComercial: 'GastroLuz',
    personaContacto: 'Ana Rodríguez',
    telefono: '+34 600 555 666',
    email: 'admin@gastroluz.com',
    direccionFiscal: 'Plaza del Sol 7, 08001 Barcelona',
    asesoresAsignados: ['2'],
    modulosActivos: {
      subidaDocumentos: true,
      incidencias: true,
      asistenteE2: true,
      panelFinanciero: true,
      facturacion: false,
    },
    estado: 'activo',
    fechaAlta: new Date('2024-03-05'),
  },
  {
    id: 'c4',
    nif: 'B55667788',
    razonSocial: 'TechSolutions SL',
    nombreComercial: 'TechSolutions',
    personaContacto: 'Pedro González',
    telefono: '+34 600 777 888',
    email: 'contacto@techsolutions.com',
    direccionFiscal: 'Calle Innovación 56, 46001 Valencia',
    asesoresAsignados: ['2'],
    modulosActivos: {
      subidaDocumentos: true,
      incidencias: true,
      asistenteE2: true,
      panelFinanciero: true,
      facturacion: true,
    },
    estado: 'activo',
    fechaAlta: new Date('2024-04-12'),
  },
  {
    id: 'c5',
    nif: 'B99887766',
    razonSocial: 'Construcciones Norte SA',
    nombreComercial: 'ConstrNorte',
    personaContacto: 'Laura Fernández',
    telefono: '+34 600 999 000',
    email: 'info@constrnorte.com',
    direccionFiscal: 'Polígono Industrial 12, 50001 Zaragoza',
    asesoresAsignados: ['2'],
    modulosActivos: {
      subidaDocumentos: true,
      incidencias: true,
      asistenteE2: false,
      panelFinanciero: true,
      facturacion: false,
    },
    estado: 'activo',
    fechaAlta: new Date('2024-05-20'),
  },
  {
    id: 'c6',
    nif: 'B12398745',
    razonSocial: 'Distribuciones Levante SL',
    nombreComercial: 'DisLevante',
    personaContacto: 'José Antonio Moreno',
    telefono: '+34 600 111 333',
    email: 'ja.moreno@dislevante.com',
    direccionFiscal: 'Calle Mayor 89, 03001 Alicante',
    asesoresAsignados: ['3'],
    modulosActivos: {
      subidaDocumentos: true,
      incidencias: true,
      asistenteE2: true,
      panelFinanciero: true,
      facturacion: false,
    },
    estado: 'activo',
    fechaAlta: new Date('2024-06-10'),
  },
  {
    id: 'c7',
    nif: 'B45612378',
    razonSocial: 'Consultoría Estratégica SA',
    nombreComercial: 'ConEstra',
    personaContacto: 'Isabel Jiménez',
    telefono: '+34 600 222 444',
    email: 'contacto@conestrategica.com',
    direccionFiscal: 'Paseo de la Castellana 200, 28046 Madrid',
    asesoresAsignados: ['3'],
    modulosActivos: {
      subidaDocumentos: true,
      incidencias: true,
      asistenteE2: true,
      panelFinanciero: true,
      facturacion: true,
    },
    estado: 'activo',
    fechaAlta: new Date('2024-07-01'),
  },
  {
    id: 'c8',
    nif: 'B78945612',
    razonSocial: 'Alimentación Gourmet SL',
    nombreComercial: 'AliGourmet',
    personaContacto: 'Francisco Ruiz',
    telefono: '+34 600 333 555',
    email: 'francisco@aligourmet.com',
    direccionFiscal: 'Mercado Central, Local 45, 29001 Málaga',
    asesoresAsignados: ['3'],
    modulosActivos: {
      subidaDocumentos: true,
      incidencias: true,
      asistenteE2: false,
      panelFinanciero: false,
      facturacion: false,
    },
    estado: 'activo',
    fechaAlta: new Date('2024-08-15'),
  },
  {
    id: 'c9',
    nif: 'B32165498',
    razonSocial: 'Servicios Integrales del Sur SL',
    nombreComercial: 'ServiSur',
    personaContacto: 'Antonio López',
    telefono: '+34 600 444 666',
    email: 'antonio@servisur.com',
    direccionFiscal: 'Avenida Andalucía 78, 18001 Granada',
    asesoresAsignados: ['4'],
    modulosActivos: {
      subidaDocumentos: true,
      incidencias: true,
      asistenteE2: true,
      panelFinanciero: true,
      facturacion: false,
    },
    estado: 'activo',
    fechaAlta: new Date('2024-09-01'),
  },
  {
    id: 'c10',
    nif: 'B65498732',
    razonSocial: 'Transportes Rápidos SA',
    nombreComercial: 'TransRápido',
    personaContacto: 'Elena Martínez',
    telefono: '+34 600 555 777',
    email: 'elena@transrapido.com',
    direccionFiscal: 'Polígono Logístico 5, 41700 Sevilla',
    asesoresAsignados: ['4'],
    modulosActivos: {
      subidaDocumentos: true,
      incidencias: true,
      asistenteE2: true,
      panelFinanciero: true,
      facturacion: true,
    },
    estado: 'activo',
    fechaAlta: new Date('2024-09-20'),
  },
];

// Mock Documentos (expandido significativamente)
export const mockDocumentos: Documento[] = [
  {
    id: 'd1',
    nombre: 'Factura_1023_Iberdrola.pdf',
    clienteId: 'c1',
    asesorId: '2',
    tipo: 'recibida_pdf',
    estado: 'pendiente',
    fechaSubida: new Date('2025-10-08'),
    procesadoIA: true,
    tamaño: 327680,
    urlArchivo: '/docs/factura1023.pdf',
    datosIA: {
      fechaFactura: '02/10/2025',
      numeroFactura: 'F-1203',
      nifEmisor: 'A12345678',
      razonSocialEmisor: 'Iberdrola SA',
      nifReceptor: 'B12345678',
      razonSocialReceptor: 'EnergíaSur SL',
      baseImponible: 1200.0,
      tipoIVA: 21,
      cuotaIVA: 252.0,
      totalFactura: 1452.0,
      nivelConfianza: 98,
      tipoDocumento: 'recibida',
    },
    incidencias: ['inc1'],
  },
  {
    id: 'd2',
    nombre: 'Factura_1024_Endesa.pdf',
    clienteId: 'c1',
    asesorId: '2',
    tipo: 'recibida_pdf',
    estado: 'contabilizado',
    fechaSubida: new Date('2025-10-05'),
    procesadoIA: true,
    tamaño: 298600,
    urlArchivo: '/docs/factura1024.pdf',
    nroAsientoERP: '2315',
    datosIA: {
      fechaFactura: '01/10/2025',
      numeroFactura: 'EN-8921',
      nifEmisor: 'A23456789',
      razonSocialEmisor: 'Endesa Energía SAU',
      nifReceptor: 'B12345678',
      razonSocialReceptor: 'EnergíaSur SL',
      baseImponible: 850.0,
      tipoIVA: 21,
      cuotaIVA: 178.5,
      totalFactura: 1028.5,
      nivelConfianza: 99,
      tipoDocumento: 'recibida',
    },
  },
  {
    id: 'd3',
    nombre: 'Factura_2001_Cliente_ABC.pdf',
    clienteId: 'c1',
    asesorId: '2',
    tipo: 'emitida_pdf',
    estado: 'validado',
    fechaSubida: new Date('2025-10-01'),
    procesadoIA: true,
    tamaño: 245800,
    urlArchivo: '/docs/factura2001.pdf',
    datosIA: {
      fechaFactura: '30/09/2025',
      numeroFactura: '2025-001',
      nifEmisor: 'B12345678',
      razonSocialEmisor: 'EnergíaSur SL',
      nifReceptor: 'B98765432',
      razonSocialReceptor: 'Cliente ABC SL',
      baseImponible: 5000.0,
      tipoIVA: 21,
      cuotaIVA: 1050.0,
      totalFactura: 6050.0,
      nivelConfianza: 97,
      tipoDocumento: 'emitida',
    },
  },
  {
    id: 'd4',
    nombre: 'Nomina_Septiembre_2025.pdf',
    clienteId: 'c2',
    asesorId: '2',
    tipo: 'otro',
    estado: 'procesado_ia',
    fechaSubida: new Date('2025-10-03'),
    procesadoIA: true,
    tamaño: 156400,
    urlArchivo: '/docs/nomina_sept.pdf',
    datosIA: {
      fechaFactura: '30/09/2025',
      nivelConfianza: 85,
      tipoDocumento: 'nomina',
    },
  },
  {
    id: 'd5',
    nombre: 'Factura_Proveedores_Mercedes.pdf',
    clienteId: 'c2',
    asesorId: '2',
    tipo: 'recibida_pdf',
    estado: 'incidencia',
    fechaSubida: new Date('2025-10-07'),
    procesadoIA: true,
    tamaño: 412000,
    urlArchivo: '/docs/factura_mercedes.pdf',
    datosIA: {
      fechaFactura: '05/10/2025',
      numeroFactura: 'MB-2025-445',
      baseImponible: 28500.0,
      tipoIVA: 21,
      cuotaIVA: 5985.0,
      totalFactura: 34485.0,
      nivelConfianza: 72,
      tipoDocumento: 'recibida',
    },
    incidencias: ['inc2'],
  },
  {
    id: 'd6',
    nombre: 'Factura_Agua_Canal_Isabel_II.pdf',
    clienteId: 'c3',
    asesorId: '2',
    tipo: 'recibida_pdf',
    estado: 'contabilizado',
    fechaSubida: new Date('2025-09-28'),
    procesadoIA: true,
    tamaño: 189200,
    urlArchivo: '/docs/agua_sept.pdf',
    nroAsientoERP: '2290',
    datosIA: {
      fechaFactura: '25/09/2025',
      numeroFactura: 'CI-092025-8876',
      nifEmisor: 'Q2878002H',
      razonSocialEmisor: 'Canal de Isabel II',
      baseImponible: 145.50,
      tipoIVA: 10,
      cuotaIVA: 14.55,
      totalFactura: 160.05,
      nivelConfianza: 96,
      tipoDocumento: 'recibida',
    },
  },
  {
    id: 'd7',
    nombre: 'Factura_Gas_Natural.pdf',
    clienteId: 'c3',
    asesorId: '2',
    tipo: 'recibida_pdf',
    estado: 'pendiente',
    fechaSubida: new Date('2025-10-10'),
    procesadoIA: true,
    tamaño: 221400,
    urlArchivo: '/docs/gas_oct.pdf',
    datosIA: {
      fechaFactura: '08/10/2025',
      numeroFactura: 'GN-10-2025-3421',
      nifEmisor: 'A08015497',
      razonSocialEmisor: 'Naturgy Energy Group SA',
      baseImponible: 320.80,
      tipoIVA: 21,
      cuotaIVA: 67.37,
      totalFactura: 388.17,
      nivelConfianza: 94,
      tipoDocumento: 'recibida',
    },
  },
  {
    id: 'd8',
    nombre: 'Factura_Alquiler_Local.pdf',
    clienteId: 'c3',
    asesorId: '2',
    tipo: 'recibida_pdf',
    estado: 'validado',
    fechaSubida: new Date('2025-10-01'),
    procesadoIA: true,
    tamaño: 195600,
    urlArchivo: '/docs/alquiler_oct.pdf',
    datosIA: {
      fechaFactura: '01/10/2025',
      numeroFactura: 'ALQ-2025-10',
      baseImponible: 1500.0,
      tipoIVA: 21,
      cuotaIVA: 315.0,
      totalFactura: 1815.0,
      nivelConfianza: 99,
      tipoDocumento: 'recibida',
    },
  },
  {
    id: 'd9',
    nombre: 'Factura_Servicios_Cliente_XYZ.pdf',
    clienteId: 'c4',
    asesorId: '2',
    tipo: 'emitida_pdf',
    estado: 'contabilizado',
    fechaSubida: new Date('2025-09-25'),
    procesadoIA: true,
    tamaño: 268900,
    urlArchivo: '/docs/servicios_xyz.pdf',
    nroAsientoERP: '2265',
    datosIA: {
      fechaFactura: '24/09/2025',
      numeroFactura: 'TS-2025-089',
      nifEmisor: 'B55667788',
      razonSocialEmisor: 'TechSolutions SL',
      baseImponible: 12000.0,
      tipoIVA: 21,
      cuotaIVA: 2520.0,
      totalFactura: 14520.0,
      nivelConfianza: 98,
      tipoDocumento: 'emitida',
    },
  },
  {
    id: 'd10',
    nombre: 'Gasto_Comida_Equipo.pdf',
    clienteId: 'c4',
    asesorId: '2',
    tipo: 'otro',
    estado: 'rechazado',
    fechaSubida: new Date('2025-10-05'),
    procesadoIA: true,
    tamaño: 89400,
    urlArchivo: '/docs/comida_equipo.pdf',
    datosIA: {
      fechaFactura: '04/10/2025',
      totalFactura: 85.50,
      nivelConfianza: 65,
      tipoDocumento: 'ticket',
    },
  },
];

// Mock Incidencias (expandido con conversaciones completas)
export const mockIncidencias: Incidencia[] = [
  {
    id: 'inc1',
    documentoId: 'd1',
    clienteId: 'c1',
    asesorId: '2',
    estado: 'en_revision',
    origen: 'ia',
    fechaCreacion: new Date('2025-10-08T22:15:00'),
    fechaUltimaRespuesta: new Date('2025-10-09T09:30:00'),
    mensajes: [
      {
        id: 'm1',
        usuarioId: 'ia',
        rol: 'admin',
        mensaje: 'Detectado NIF ilegible en factura. El NIF del emisor no se ha podido leer correctamente. Nivel de confianza: 78%. Se requiere revisión manual.',
        fecha: new Date('2025-10-08T22:15:00'),
      },
      {
        id: 'm2',
        usuarioId: '2',
        rol: 'asesor',
        mensaje: 'Hola María, hemos detectado que el NIF en la factura de Iberdrola no se lee bien. ¿Podrías verificar y subirnos una copia más nítida?',
        fecha: new Date('2025-10-09T08:45:00'),
      },
      {
        id: 'm3',
        usuarioId: '5',
        rol: 'cliente',
        mensaje: 'Buenos días Marta, disculpa las molestias. Te subo ahora mismo una copia escaneada de mejor calidad.',
        fecha: new Date('2025-10-09T09:30:00'),
      },
    ],
  },
  {
    id: 'inc2',
    documentoId: 'd5',
    clienteId: 'c2',
    asesorId: '2',
    estado: 'nueva',
    origen: 'ia',
    fechaCreacion: new Date('2025-10-07T23:45:00'),
    mensajes: [
      {
        id: 'm4',
        usuarioId: 'ia',
        rol: 'admin',
        mensaje: 'Incoherencia detectada: La suma de Base + IVA no coincide con el Total declarado. Base: 28.500€, IVA (21%): 5.985€, Total calculado: 34.485€, pero el documento muestra 34.400€. Diferencia: 85€.',
        fecha: new Date('2025-10-07T23:45:00'),
      },
    ],
  },
  {
    id: 'inc3',
    documentoId: 'd4',
    clienteId: 'c2',
    asesorId: '2',
    estado: 'resuelta',
    origen: 'asesor',
    fechaCreacion: new Date('2025-10-04T10:20:00'),
    fechaUltimaRespuesta: new Date('2025-10-05T11:15:00'),
    mensajes: [
      {
        id: 'm5',
        usuarioId: '2',
        rol: 'asesor',
        mensaje: 'Falta documentación complementaria: necesitamos el justificante de pago de la Seguridad Social correspondiente a esta nómina.',
        fecha: new Date('2025-10-04T10:20:00'),
      },
      {
        id: 'm6',
        usuarioId: 'c2',
        rol: 'cliente',
        mensaje: 'Perfecto, lo subo ahora mismo. Gracias por avisar.',
        fecha: new Date('2025-10-04T16:30:00'),
      },
      {
        id: 'm7',
        usuarioId: '2',
        rol: 'asesor',
        mensaje: 'Recibido y validado. Cerramos la incidencia. ¡Gracias!',
        fecha: new Date('2025-10-05T11:15:00'),
      },
    ],
  },
  {
    id: 'inc4',
    documentoId: 'd10',
    clienteId: 'c4',
    asesorId: '2',
    estado: 'cerrada',
    origen: 'asesor',
    fechaCreacion: new Date('2025-10-06T14:00:00'),
    fechaUltimaRespuesta: new Date('2025-10-06T15:30:00'),
    mensajes: [
      {
        id: 'm8',
        usuarioId: '2',
        rol: 'asesor',
        mensaje: 'Este ticket de comida no cumple los requisitos fiscales para ser deducible. No aparece el NIF del establecimiento ni la descripción detallada del gasto.',
        fecha: new Date('2025-10-06T14:00:00'),
      },
      {
        id: 'm9',
        usuarioId: 'c4',
        rol: 'cliente',
        mensaje: 'Entendido. Lo descarto entonces. Gracias por la aclaración.',
        fecha: new Date('2025-10-06T15:30:00'),
      },
    ],
  },
];

// Mock Métricas Dashboard
export const mockMetricas: MetricasDashboard = {
  documentosPendientes: 145,
  facturasIA: 327,
  incidenciasAbiertas: 12,
  clientesActivos: 84,
  asesoresActivos: 9,
};

// Mock Actividad Reciente
export const mockActividad: ActividadReciente[] = [
  {
    id: 'a1',
    tipo: 'documento',
    descripcion: 'Asesor Marta contabilizó 12 documentos de Cliente EnergíaSur SL',
    usuario: 'Marta López',
    fecha: new Date('2025-10-23T10:23:00'),
  },
  {
    id: 'a2',
    tipo: 'incidencia',
    descripcion: 'La IA marcó 3 incidencias automáticas',
    usuario: 'Sistema IA',
    fecha: new Date('2025-10-23T09:15:00'),
  },
  {
    id: 'a3',
    tipo: 'documento',
    descripcion: 'Cliente ComexPro SL subió 5 facturas nuevas',
    usuario: 'ComexPro SL',
    fecha: new Date('2025-10-22T16:45:00'),
  },
  {
    id: 'a4',
    tipo: 'usuario',
    descripcion: 'Nuevo cliente TechSolutions SL dado de alta',
    usuario: 'Admin Principal',
    fecha: new Date('2025-10-22T14:30:00'),
  },
  {
    id: 'a5',
    tipo: 'contabilizacion',
    descripcion: 'Generado Libro Registro de Facturas para GastroLuz SL (28 documentos)',
    usuario: 'Marta López',
    fecha: new Date('2025-10-22T12:00:00'),
  },
  {
    id: 'a6',
    tipo: 'incidencia',
    descripcion: 'Incidencia INC-1045 marcada como resuelta',
    usuario: 'Luis Pérez',
    fecha: new Date('2025-10-22T11:15:00'),
  },
  {
    id: 'a7',
    tipo: 'documento',
    descripcion: 'Cliente Distribuciones Levante SL subió 15 documentos',
    usuario: 'DisLevante',
    fecha: new Date('2025-10-21T18:20:00'),
  },
];

// Mock Datos Financieros (expandido)
export const mockDatosFinancieros: DatosFinancieros[] = [
  {
    clienteId: 'c1',
    periodo: 'Q3 2025',
    ingresos: 230000,
    gastos: 190000,
    resultado: 40000,
    margen: 17.4,
    riesgoIA: 'bajo',
    ultimoCierre: new Date('2025-09-30'),
  },
  {
    clienteId: 'c2',
    periodo: 'Q3 2025',
    ingresos: 120000,
    gastos: 118000,
    resultado: 2000,
    margen: 1.6,
    riesgoIA: 'medio',
    ultimoCierre: new Date('2025-09-30'),
  },
  {
    clienteId: 'c3',
    periodo: 'Q3 2025',
    ingresos: 310000,
    gastos: 345000,
    resultado: -35000,
    margen: -11.2,
    riesgoIA: 'alto',
    ultimoCierre: new Date('2025-09-30'),
  },
  {
    clienteId: 'c4',
    periodo: 'Q3 2025',
    ingresos: 450000,
    gastos: 320000,
    resultado: 130000,
    margen: 28.9,
    riesgoIA: 'bajo',
    ultimoCierre: new Date('2025-09-30'),
  },
  {
    clienteId: 'c5',
    periodo: 'Q3 2025',
    ingresos: 680000,
    gastos: 598000,
    resultado: 82000,
    margen: 12.1,
    riesgoIA: 'bajo',
    ultimoCierre: new Date('2025-09-30'),
  },
  {
    clienteId: 'c6',
    periodo: 'Q3 2025',
    ingresos: 275000,
    gastos: 245000,
    resultado: 30000,
    margen: 10.9,
    riesgoIA: 'bajo',
    ultimoCierre: new Date('2025-09-30'),
  },
  {
    clienteId: 'c7',
    periodo: 'Q3 2025',
    ingresos: 520000,
    gastos: 410000,
    resultado: 110000,
    margen: 21.2,
    riesgoIA: 'bajo',
    ultimoCierre: new Date('2025-09-30'),
  },
  {
    clienteId: 'c8',
    periodo: 'Q3 2025',
    ingresos: 185000,
    gastos: 175000,
    resultado: 10000,
    margen: 5.4,
    riesgoIA: 'medio',
    ultimoCierre: new Date('2025-09-30'),
  },
  {
    clienteId: 'c9',
    periodo: 'Q3 2025',
    ingresos: 390000,
    gastos: 365000,
    resultado: 25000,
    margen: 6.4,
    riesgoIA: 'medio',
    ultimoCierre: new Date('2025-09-30'),
  },
  {
    clienteId: 'c10',
    periodo: 'Q3 2025',
    ingresos: 825000,
    gastos: 712000,
    resultado: 113000,
    margen: 13.7,
    riesgoIA: 'bajo',
    ultimoCierre: new Date('2025-09-30'),
  },
];

// Función auxiliar para obtener cliente por ID
export const getClienteById = (id: string): Cliente | undefined => {
  return mockClientes.find(c => c.id === id);
};

// Función auxiliar para obtener documentos por cliente
export const getDocumentosByCliente = (clienteId: string): Documento[] => {
  return mockDocumentos.filter(d => d.clienteId === clienteId);
};

// Función auxiliar para obtener incidencias por cliente
export const getIncidenciasByCliente = (clienteId: string): Incidencia[] => {
  return mockIncidencias.filter(i => i.clienteId === clienteId);
};

// Función auxiliar para obtener datos financieros por cliente
export const getDatosFinancierosByCliente = (clienteId: string): DatosFinancieros | undefined => {
  return mockDatosFinancieros.find(df => df.clienteId === clienteId);
};
